package ProyectoSI;

import jade.gui.GuiEvent;
import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Mario A. Yusti
 */
public class GUIJuego extends javax.swing.JFrame {

    private final AgenteTablero agente;

    /**
     * Creates new form GUIJuego
     *
     * @param _agente
     */
    public GUIJuego(AgenteTablero _agente) {
        initComponents();
        this.agente = _agente;
        this.panel_Juego1.setAgente(_agente);
        this.setResizable(false);
        this.setLocationRelativeTo(this);
    }

    public void colocarFicha(boolean turnoJ1, int idPunto) {
        this.addLog("Jugador " + (turnoJ1 ? 1 : 2) + " - Coloca una ficha en el punto " + idPunto);
        this.panel_Juego1.colocarFicha(idPunto);
    }

    public void moverFicha(boolean turnoJ1, int idFicha, int idPunto) {
        this.addLog("Jugador " + (turnoJ1 ? 1 : 2) + " - Mueve la ficha " + idFicha + " al punto " + idPunto);
        this.panel_Juego1.moverFicha(idFicha, idPunto);
    }

    public void goToJuego() {
        this.jTabbedPane4.setSelectedIndex(0);
    }

    public String getJugador1Name() {
        return this.jTextField_J1.getText();
    }

    public String getJugador2Name() {
        return this.jTextField_J2.getText();
    }

    public void setEstadoJ1(boolean isConected) {
        if (isConected) {
            this.jLabel_estado_J1.setText("Conectado");
            this.jLabel_estado_J1.setForeground(Color.GREEN);
            this.jButton_Conectar_J1.setEnabled(false);
            this.jTextField_J1.setEnabled(false);
            checkTodosConectados();
        } else {
            this.jLabel_estado_J1.setText("Desconectado");
            this.jLabel_estado_J1.setForeground(Color.RED);
        }
    }

    public void setEstadoJ2(boolean isConected) {
        if (isConected) {
            this.jLabel_estado_J2.setText("Conectado");
            this.jLabel_estado_J2.setForeground(Color.GREEN);
            this.jButton_Conectar_J2.setEnabled(false);
            this.jTextField_J2.setEnabled(false);
            checkTodosConectados();
        } else {
            this.jLabel_estado_J2.setText("Desconectado");
            this.jLabel_estado_J2.setForeground(Color.RED);
        }
    }

    public void checkTodosConectados() {
        if (this.agente.isJugador1Conectado() && this.agente.isJugador2Conectado()) {
            this.jButton_Jugar.setEnabled(true);
        }
    }

    public void addLog(String log) {
        this.jTextArea_Log.append("\n" + log);
    }

    public void actualizarGUI() {
        this.panel_Juego1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        panel_Juego1 = new ProyectoSI.Panel_Juego();
        jPanel_Configuration = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_J1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel_estado_J1 = new javax.swing.JLabel();
        jButton_Conectar_J1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_J2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel_estado_J2 = new javax.swing.JLabel();
        jButton_Conectar_J2 = new javax.swing.JButton();
        jLabel_color_J1 = new javax.swing.JLabel();
        jLabel_color_J2 = new javax.swing.JLabel();
        jButton_Jugar = new javax.swing.JButton();
        jButton_Reiniciar = new javax.swing.JButton();
        jCheckBox_ShowPointsNumbers = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Log = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_Juego1.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout panel_Juego1Layout = new javax.swing.GroupLayout(panel_Juego1);
        panel_Juego1.setLayout(panel_Juego1Layout);
        panel_Juego1Layout.setHorizontalGroup(
            panel_Juego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        panel_Juego1Layout.setVerticalGroup(
            panel_Juego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Juego", panel_Juego1);

        jLabel1.setText("Jugador 1:");

        jTextField_J1.setText("J1");

        jLabel2.setText("Estado:");

        jLabel_estado_J1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_estado_J1.setText("Desconectado");

        jButton_Conectar_J1.setText("Conectar Jugador 1");
        jButton_Conectar_J1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Conectar_J1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Jugador 2:");

        jTextField_J2.setText("J2");

        jLabel5.setText("Estado:");

        jLabel_estado_J2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_estado_J2.setText("Desconectado");

        jButton_Conectar_J2.setText("Conectar Jugador 2");
        jButton_Conectar_J2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Conectar_J2ActionPerformed(evt);
            }
        });

        jLabel_color_J1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_color_J1.setText(" ");
        jLabel_color_J1.setOpaque(true);
        jLabel_color_J1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_color_J1MouseClicked(evt);
            }
        });

        jLabel_color_J2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_color_J2.setText(" ");
        jLabel_color_J2.setOpaque(true);
        jLabel_color_J2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_color_J2MouseClicked(evt);
            }
        });

        jButton_Jugar.setText("Jugar");
        jButton_Jugar.setEnabled(false);
        jButton_Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_JugarActionPerformed(evt);
            }
        });

        jButton_Reiniciar.setText("Reiniciar");
        jButton_Reiniciar.setEnabled(false);
        jButton_Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ReiniciarActionPerformed(evt);
            }
        });

        jCheckBox_ShowPointsNumbers.setText("Mostrar el número de los Puntos");
        jCheckBox_ShowPointsNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ShowPointsNumbersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ConfigurationLayout = new javax.swing.GroupLayout(jPanel_Configuration);
        jPanel_Configuration.setLayout(jPanel_ConfigurationLayout);
        jPanel_ConfigurationLayout.setHorizontalGroup(
            jPanel_ConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConfigurationLayout.createSequentialGroup()
                .addGroup(jPanel_ConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ConfigurationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel_ConfigurationLayout.createSequentialGroup()
                        .addGroup(jPanel_ConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ConfigurationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_ConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_ConfigurationLayout.createSequentialGroup()
                                        .addGroup(jPanel_ConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel_ConfigurationLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel_ConfigurationLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel_estado_J1))
                                            .addComponent(jButton_Conectar_J1)
                                            .addGroup(jPanel_ConfigurationLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_J2)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel_ConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel_color_J1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                                            .addComponent(jLabel_color_J2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel_ConfigurationLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_estado_J2))
                                    .addComponent(jButton_Conectar_J2)))
                            .addGroup(jPanel_ConfigurationLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jButton_Jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_ConfigurationLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jCheckBox_ShowPointsNumbers)))
                        .addGap(0, 135, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_ConfigurationLayout.setVerticalGroup(
            jPanel_ConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConfigurationLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel_ConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_color_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_estado_J1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Conectar_J1)
                .addGap(86, 86, 86)
                .addGroup(jPanel_ConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_color_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_estado_J2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Conectar_J2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jCheckBox_ShowPointsNumbers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel_ConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Reiniciar)
                    .addComponent(jButton_Jugar))
                .addGap(62, 62, 62))
        );

        jTabbedPane4.addTab("Configuración", jPanel_Configuration);

        jTextArea_Log.setEditable(false);
        jTextArea_Log.setColumns(20);
        jTextArea_Log.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Log);

        jTabbedPane4.addTab("Log", jScrollPane1);

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel9.setText("Proyecto de Sistema Inteligentes I - 2019-1 - Mario Andrés Yusti Mejia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Conectar_J1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Conectar_J1ActionPerformed
        GuiEvent ge = new GuiEvent(this.agente, 1);
        this.agente.postGuiEvent(ge);
    }//GEN-LAST:event_jButton_Conectar_J1ActionPerformed

    private void jButton_Conectar_J2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Conectar_J2ActionPerformed
        GuiEvent ge = new GuiEvent(this.agente, 2);
        this.agente.postGuiEvent(ge);
    }//GEN-LAST:event_jButton_Conectar_J2ActionPerformed

    private void jLabel_color_J2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_color_J2MouseClicked
        Color newColor = JColorChooser.showDialog(this, "Seleccione el color de las fichas del Jugador 2", this.jLabel_color_J2.getBackground());
        if (newColor != null) {
            this.jLabel_color_J2.setBackground(newColor);
            this.panel_Juego1.setColorJugador2(newColor);
            this.panel_Juego1.repaint();
        }
    }//GEN-LAST:event_jLabel_color_J2MouseClicked

    private void jLabel_color_J1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_color_J1MouseClicked
        Color newColor = JColorChooser.showDialog(this, "Seleccione el color de las fichas del Jugador 1", this.jLabel_color_J1.getBackground());
        if (newColor != null) {
            this.jLabel_color_J1.setBackground(newColor);
            this.panel_Juego1.setColorJugador1(newColor);
            this.panel_Juego1.repaint();
        }
    }//GEN-LAST:event_jLabel_color_J1MouseClicked

    private void jButton_JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_JugarActionPerformed
        GuiEvent ge = new GuiEvent(this.agente, 3);
        this.agente.postGuiEvent(ge);
        this.jButton_Jugar.setEnabled(false);
        this.jButton_Reiniciar.setEnabled(true);
    }//GEN-LAST:event_jButton_JugarActionPerformed

    private void jCheckBox_ShowPointsNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ShowPointsNumbersActionPerformed
        this.panel_Juego1.ShowPoints(this.jCheckBox_ShowPointsNumbers.isSelected());
        this.goToJuego();
    }//GEN-LAST:event_jCheckBox_ShowPointsNumbersActionPerformed

    private void jButton_ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ReiniciarActionPerformed
        GuiEvent ge = new GuiEvent(this.agente, 4);
        this.agente.postGuiEvent(ge);
        this.jButton_Jugar.setEnabled(true);
        this.jButton_Reiniciar.setEnabled(false);
        this.jTextArea_Log.setText("");
        this.panel_Juego1.repaint();
    }//GEN-LAST:event_jButton_ReiniciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Conectar_J1;
    private javax.swing.JButton jButton_Conectar_J2;
    private javax.swing.JButton jButton_Jugar;
    private javax.swing.JButton jButton_Reiniciar;
    private javax.swing.JCheckBox jCheckBox_ShowPointsNumbers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_color_J1;
    private javax.swing.JLabel jLabel_color_J2;
    private javax.swing.JLabel jLabel_estado_J1;
    private javax.swing.JLabel jLabel_estado_J2;
    private javax.swing.JPanel jPanel_Configuration;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextArea jTextArea_Log;
    private javax.swing.JTextField jTextField_J1;
    private javax.swing.JTextField jTextField_J2;
    private ProyectoSI.Panel_Juego panel_Juego1;
    // End of variables declaration//GEN-END:variables
}
